package edu.ccnt.mymall.model;

import java.util.Date;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_category.id
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_category.parent_id
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_category.name
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_category.status
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_category.sort_order
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    private Integer sortOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_category.create_time
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mmall_category.update_time
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_category.id
     *
     * @return the value of mmall_category.id
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_category.id
     *
     * @param id the value for mmall_category.id
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_category.parent_id
     *
     * @return the value of mmall_category.parent_id
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_category.parent_id
     *
     * @param parentId the value for mmall_category.parent_id
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_category.name
     *
     * @return the value of mmall_category.name
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_category.name
     *
     * @param name the value for mmall_category.name
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_category.status
     *
     * @return the value of mmall_category.status
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_category.status
     *
     * @param status the value for mmall_category.status
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_category.sort_order
     *
     * @return the value of mmall_category.sort_order
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public Integer getSortOrder() {
        return sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_category.sort_order
     *
     * @param sortOrder the value for mmall_category.sort_order
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public void setSortOrder(Integer sortOrder) {
        this.sortOrder = sortOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_category.create_time
     *
     * @return the value of mmall_category.create_time
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_category.create_time
     *
     * @param createTime the value for mmall_category.create_time
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mmall_category.update_time
     *
     * @return the value of mmall_category.update_time
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mmall_category.update_time
     *
     * @param updateTime the value for mmall_category.update_time
     *
     * @mbg.generated Wed Aug 02 21:00:02 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}